# Generated by Django 5.1 on 2024-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_application_number', models.IntegerField()),
                ('academic_year', models.CharField(max_length=100)),
                ('application_opened_date', models.DateField()),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town_city_village', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=10)),
                ('stdcode', models.CharField(max_length=10)),
                ('landline_number', models.BigIntegerField()),
                ('apply_new_odl', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('parent_application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_running_institute', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('land_details', models.IntegerField()),
                ('building_details', models.TextField()),
                ('total_ter_charges', models.CharField(max_length=100)),
                ('total_amount_paid', models.CharField(max_length=100)),
                ('late_fee', models.CharField(max_length=100)),
                ('balance_amount_to_be_paid', models.CharField(max_length=100)),
            ],
        ),
    ]
