# Generated by Django 5.1 on 2024-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0003_institution_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_plan_approval', models.FileField(blank=True, null=True, upload_to='documents/building_plan_approval/')),
                ('occupancy_certificate', models.FileField(blank=True, null=True, upload_to='documents/occupancy_certificate/')),
                ('title_document', models.FileField(blank=True, null=True, upload_to='documents/title_document/')),
                ('lease_deed', models.FileField(blank=True, null=True, upload_to='documents/lease_deed/')),
                ('fire_safety_certificate', models.FileField(blank=True, null=True, upload_to='documents/fire_safety_certificate/')),
                ('land_use_certificate', models.FileField(blank=True, null=True, upload_to='documents/land_use_certificate/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='documents/floor_plan/')),
                ('proof_of_working_capital', models.FileField(blank=True, null=True, upload_to='documents/proof_of_working_capital/')),
                ('audited_statement', models.FileField(blank=True, null=True, upload_to='documents/audited_statement/')),
                ('minority_status_certificate', models.FileField(blank=True, null=True, upload_to='documents/minority_status_certificate/')),
                ('detailed_project_report', models.FileField(blank=True, null=True, upload_to='documents/detailed_project_report/')),
                ('undertaking_form', models.FileField(blank=True, null=True, upload_to='documents/undertaking_form/')),
            ],
        ),
    ]
